### PR TITLE
fix: es export entry. 

### LINKED ISSUE #13: package.json "module" field breaks transpiling
hi the recent 1.4.0 release added the "module" field in package.json but now when css-animation is a dependency of a create-react-app project the build fails with 
> 'css-animation' does not contain an export named 'isCssAnimationSupported'.

the issue is that isCssAnimationSupported is exported as a field of the default export
i don't know why but before the package.json modification the following import worked
`{isCssAnimationSupported} from "css-animation"` 

is possible to add the named export:
`export isCssAnimationSupported`
to be backward compatible?
tnx

### LINKED ISSUE #14: 'css-animation' does not contain an export named 'isCssAnimationSupported'.
Hi!
I've been using `rc-slider` package, and I got following error 

> ./node_modules/rc-animate/es/AnimateChild.js
> 76:11-34 'css-animation' does not contain an export named 'isCssAnimationSupported'.

As listed in `npm list` command, it uses internally Your package

> ├─┬ rc-slider@8.3.1
> │ ├── classnames@2.2.5
> │ ├─┬ rc-tooltip@3.4.8
> │ │   └─┬ rc-trigger@1.11.3
> │ │        ├─┬ rc-align@2.3.4
> │ │             └── dom-align@1.6.3
> │ │        └─┬ rc-animate@2.4.1
> │ │              └─┬ css-animation@1.4.0
> │ │                    └─┬ component-classes@1.2.6
> │ │                          └── component-indexof@0.0.3

Code worked on version `1.3.2` and stopped working on version `1.4.0`

In `rc-animate` package, import from `css-animation` looks like this:

`import cssAnimate, { isCssAnimationSupported } from 'css-animation';`

Did something change in the API?

### PR DESCRIPTION
**Pull request by paranoidjk**
https://github.com/react-component/animate/blob/master/src/AnimateChild.js#L4

close #14 
close #13

### CODE REVIEW

**Comment by paranoidjk** [comment]
@yiminghe

**Comment by paranoidjk** [comment]
close https://github.com/react-component/slider/issues/309

close https://github.com/react-component/tooltip/issues/94

**Comment by paranoidjk** [comment]
close https://github.com/react-component/animate/issues/30

File: src/index.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import Event from './Event';
 import classes from 'component-classes';
 
-const isCssAnimationSupported = Event.endEvents.length !== 0;
+export const isCssAnimationSupported = Event.endEvents.length !== 0;
```
Comment (paranoidjk) [inline src/index.js]: @yiminghe 主要改动就是把这个 export 出去

不确定有多少库会这样引用了 https://github.com/react-component/animate/blob/master/src/AnimateChild.js#L4
